### ISSUE TITLE
Need information about Gitness development stage

### ISSUE THREAD

**Issue by JeanFSorio** [harness/gitness#3384]
In the README it's mentioned:

> Drone development will continue in the drone branch until we a ready for our first tagged Gitness release, at which point the project will fully converge.

I'm here to question about the current stage of Gitness development. I've tested it, and it worked well. However, couldn't find information in the README or the docs regarding whether it's production-ready. I apologize if I've missed this information.

**Comment by bradrydzewski** [comment]
hey @JeanFSorio the product is pretty reliable, but I would still describe the current state as Beta, mainly because we are still working to improve the documentation, there are still. some minor bugs, and we could make some very minor (breaking) changes to the yaml syntax in the coming weeks.

We have been using Gitness code hosting internally for the past 6 months, if that helps.  But Gitness Pipelines just landed and we are still in the testing phase.

If you are currently using Drone, it will probably take around 6 months before you can upgrade your Drone instance to Gitness with full feature parity.  The end goal is a seamless product merge and seamless upgrade experience, with zero migration required.

**Comment by JeanFSorio** [comment]
Thank you! I've been facing challenges with our current Git setup at work, as we lack code review and pipelines. I came across Gitness in a newsletter and wanted to explore it. I'll keep an eye on the updates and possibly suggest it to my boss as a solution for our needs. Thanks again!
