### ISSUE TITLE
Slack join invitation is not working

### ISSUE THREAD

**Issue by mudasirmirza** [harness/gitness#3413]
Hi,

The Slack invitation link in the documentation is not valid
https://join.slack.com/t/harnesscommunity/shared_invite/zt-y4hdqh7p-RVuEQyIl5Hcx4Ck8VCvzBw

Can we have a valid link, would love to join Drone Slack Community

**Comment by bradrydzewski** [comment]
this has been fixed.  it was caused due to some weird policy where Slack expires the invitation link after 400 clicks.  We generated a new link and added here https://docs.gitness.com/support

we are working on getting Slack to generate a link that will expire after 4000 clicks, which is better, but unfortunately this problem may crop up every so often unless Slack provides an option for non-expiring links.
