### ISSUE TITLE
Gitness - Unauthenticated Git Pulls

### ISSUE THREAD

**Issue by golyalpha** [harness/gitness#3529]
When setting a repository to Public under Gitness (which is described as "Anyone with access to the Gitness environment can clone this repo"), browsing the repository via the Web UI is not possible, however, unauthenticated git pulls are.

Personally, I'd be fine if Public on Gitness meant what Protected/Internal means everywhere else (if you can log in to Gitness, you can see and work with the repo), but this is a weird combination of both Public as in "everyone in the world" (can git pull), and Public as in "everyone with an account" (can see the repo in their browser)...

Is this a bug, or is this intended behaviour? It might be worthwhile to clarify the note on the visibility level if this is intended - point out that you don't need an account to do a pull.

**Comment by bradrydzewski** [comment]
This is due to incremental development / shipping subsets of features when they are ready. The backend team added support for public clone because it was relatively simple.  However, the effort to update the frontend to no longer require an authenticated user is a much larger effort, which means it will ship in a later release.

Merging with https://github.com/harness/gitness/issues/3521
